server:
  port: 8081

logging:
  level:
    root: INFO
    com.example.b: INFO
  config: classpath:logback-spring.xml

management:
  endpoints:
    web:
      exposure:
        include: [health, info, metrics]
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
