apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  labels:
    app: otel-collector
data:
  otel-collector-config.yml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          scrape_configs:
            - job_name: 'service-a'
              static_configs:
                - targets: ['service-a:8080']
              metrics_path: '/actuator/prometheus'
              scrape_interval: 5s
            - job_name: 'service-b'
              static_configs:
                - targets: ['service-b:8081']
              metrics_path: '/actuator/prometheus'
              scrape_interval: 5s

    exporters:
      prometheus:
        endpoint: "0.0.0.0:9464"
      debug:
        verbosity: detailed

    service:
      pipelines:
        metrics:
          receivers: [otlp, prometheus]
          exporters: [prometheus, debug]
        traces:
          receivers: [otlp]
          exporters: [debug]