apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resilience4j-stack.fullname" . }}-grafana-secret
  labels:
    {{- include "resilience4j-stack.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.grafana.adminPassword | b64enc | quote }}