{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prometheus.name }}-config
  labels:
    app: {{ .Values.prometheus.name }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.config.scrapeInterval }}
      evaluation_interval: {{ .Values.prometheus.config.evaluationInterval }}

    scrape_configs:
      - job_name: 'service-a'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['{{ .Values.serviceA.name }}:{{ .Values.serviceA.service.port }}']

      - job_name: 'service-b'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['{{ .Values.serviceB.name }}:{{ .Values.serviceB.service.port }}']

      - job_name: 'otel-collector'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['{{ .Values.otelCollector.name }}:{{ .Values.otelCollector.service.ports.prometheusMetrics }}']
{{- end }}