apiVersion: v1
kind: Namespace
metadata:
  name: resilience4j-aws-multi
  labels:
    environment: aws
    deployment-type: multi-node
    node-count: "2"
    app.kubernetes.io/name: resilience4j
    app.kubernetes.io/instance: aws-multi