services:
  service-b:
    image: r4j-sample-service-b:0.1.0
    container_name: service-b
    ports:
      - "8081:8081"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_SERVICE_NAME=service-b
      - OTEL_RESOURCE_ATTRIBUTES=service.name=service-b,service.version=0.1.0
    depends_on:
      - otel-collector
    networks:
      - r4j-net

  service-a:
    image: r4j-sample-service-a:0.1.0
    container_name: service-a
    ports:
      - "8080:8080"
    environment:
      - B_URL=http://service-b:8081
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_SERVICE_NAME=service-a
      - OTEL_RESOURCE_ATTRIBUTES=service.name=service-a,service.version=0.1.0
    depends_on:
      - service-b
      - otel-collector
    networks:
      - r4j-net

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - r4j-net

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - r4j-net

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.109.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./configs/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4318:4318"   # OTLP HTTP (metrics)
      - "9464:9464"   # Prometheus metrics exporter
      - "8888:8888"   # Internal metrics
    networks:
      - r4j-net

networks:
  r4j-net:
    driver: bridge