global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'service-a'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['service-a:8080']

  - job_name: 'service-b'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['service-b:8081']

  - job_name: 'otel-collector'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['otel-collector:9464']

  - job_name: 'otel-collector-internal'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['otel-collector:8888']