global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']
    scrape_interval: 10s
    metrics_path: '/metrics'

  - job_name: 'otel-collector-internal'
    static_configs:
      - targets: ['otel-collector:8888']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'service-a'
    static_configs:
      - targets: ['service-a:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  - job_name: 'service-b'
    static_configs:
      - targets: ['service-b:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    scrape_interval: 30s
    metrics_path: '/metrics'