apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:latest
        ports:
        - containerPort: 4318
          name: otlp-http
        - containerPort: 9464
          name: prometheus
        # Mount configuration from ConfigMap
        volumeMounts:
        - name: otel-config
          mountPath: /etc/otel-collector-config.yml
          subPath: otel-collector-config.yml
        # Override default command to use mounted config
        args: ["--config=/etc/otel-collector-config.yml"]
        # Resource limits
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      # Volume definition for ConfigMap
      volumes:
      - name: otel-config
        configMap:
          name: otel-collector-config