apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: otel-collector
spec:
  type: ClusterIP  # Internal cluster access only
  ports:
  - port: 4318
    targetPort: 4318
    protocol: TCP
    name: otlp-http
  - port: 9464
    targetPort: 9464
    protocol: TCP
    name: prometheus
  selector:
    app: otel-collector